apiVersion: xl-deploy/v1
kind: Applications
spec:
- name: aws-ecommerce
  type: core.Directory
  children:
    - name: K8S
      type: core.Directory
      children:
      - name: aws-ecommerce-store-mysql
        type: udm.Application
        children:
        - name: !value BUILD_ID
          type: udm.DeploymentPackage
          deployables:
          - name: aws-ecommerce-store-mysql
            type: k8s.ResourcesFile
            file: !file ../store/build/kubernetes/store-mysql.yml
            tags: 
            - xl-demo
      - name: aws-ecommerce-registry
        type: udm.Application
        children:
        - name: !value BUILD_ID
          type: udm.DeploymentPackage
          deployables:
          - name: aws-ecommerce-application-config
            type: k8s.ResourcesFile
            file: !file ../registry/kubernetes/application-configmap.yml
            tags: 
            - xl-demo
          - name: aws-ecommerce-jhipster-registry
            type: k8s.ResourcesFile
            file: !file ../registry/kubernetes/jhipster-registry.yml
            tags: 
            - xl-demo
      - name: aws-ecommerce-store
        type: udm.Application
        children:
        - name: !value BUILD_ID
          type: udm.DeploymentPackage
          deployables:
          - name: aws-ecommerce-store-deployment
            type: k8s.ResourcesFile
            file: !file ../store/build/kubernetes/store-deployment.yml
            tags: 
            - xl-demo
          - name: aws-ecommerce-store-svc
            type: k8s.ResourcesFile
            file: !file ../store/build/kubernetes/store-service.yml
            tags: 
            - xl-demo