version: '3.7'
services:
  xl-deploy:
    image: xebialabs/xl-deploy:9.0
    ports:
    - "4516:4516"
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
  xl-release:
    image: xebialabs/xl-release:9.0
    ports:
    - "5516:5516"
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y
  xl-cli:
    image: xebialabsunsupported/xl-cli:9.0
    depends_on:
    - xl-deploy
    - xl-release
    command: ["apply", "--xl-deploy-url", "http://xl-deploy:4516/", "--xl-release-url", "http://xl-release:5516/", "-f", "/data/configure-xl-devops-platform.yaml"]
    volumes:
    - ./data/:/data:ro  
  jenkins:
    image: xebialabsunsupported/jenkins-blueprint-demo:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - GITHUB_USER=${GITHUB_USER}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - DOCKER_USER=${DOCKER_USER}
      - DOCKER_PASS=${DOCKER_PASS}
    ports:
      - 8080:8080
      - 55888:55888